# capsule version
version = "0.9.0 81e9876"
# path of deployment config file
deployment = "deployment.toml"

[rust]
# path of rust contracts workspace directory,
# a `Cargo.toml` file is expected under the directory.
workspace_dir = "."
toolchain = "nightly-2021-12-25"
docker_image = "thewawar/ckb-capsule:2021-12-25"

[[contracts]]
name = "sub-account-custom-script"
template_type = "Rust"
